// Generates site/js/map-geometry.js: the four PATH states as SVG paths plus the
// projection constants map.js uses to place markers from lat/lng.
//
//   cd tools && npm install && npm run build-map
//
// Projection is equirectangular scaled by cos(reference latitude) — at this
// size the distortion is negligible and the math stays trivial at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";

const STATES = { "40": "Oklahoma", "29": "Missouri", "20": "Kansas", "05": "Arkansas" };
const WIDTH = 1000;
const PAD = 12;
const LAT_REF = 37;

const topo = JSON.parse(readFileSync(new URL("./node_modules/us-atlas/states-10m.json", import.meta.url)));
const states = feature(topo, topo.objects.states).features.filter((f) => STATES[f.id]);

const rings = (g) => (g.type === "Polygon" ? [g.coordinates] : g.coordinates).flat();
let [minLon, minLat, maxLon, maxLat] = [Infinity, Infinity, -Infinity, -Infinity];
for (const s of states)
  for (const ring of rings(s.geometry))
    for (const [lon, lat] of ring) {
      minLon = Math.min(minLon, lon); maxLon = Math.max(maxLon, lon);
      minLat = Math.min(minLat, lat); maxLat = Math.max(maxLat, lat);
    }

const kx = Math.cos((LAT_REF * Math.PI) / 180);
const scale = (WIDTH - 2 * PAD) / ((maxLon - minLon) * kx);
const height = Math.round((maxLat - minLat) * scale + 2 * PAD);
const project = ([lon, lat]) => [PAD + (lon - minLon) * kx * scale, PAD + (maxLat - lat) * scale];

const round = (n) => Math.round(n * 10) / 10;
const toPath = (geom) =>
  rings(geom)
    .map((ring) => {
      const pts = [];
      for (const p of ring) {
        const [x, y] = project(p).map(round);
        const last = pts[pts.length - 1];
        if (!last || last[0] !== x || last[1] !== y) pts.push([x, y]);
      }
      return "M" + pts.map((p) => p.join(",")).join("L") + "Z";
    })
    .join("");

const out = {
  width: WIDTH,
  height,
  projection: { minLon, maxLat, kx, scale, pad: PAD },
  states: states.map((s) => ({ name: STATES[s.id], d: toPath(s.geometry) })),
};

writeFileSync(
  new URL("../site/js/map-geometry.js", import.meta.url),
  "// Generated by tools/build-map.mjs — do not edit by hand.\nexport default " + JSON.stringify(out) + ";\n"
);
console.log(`wrote map-geometry.js (${WIDTH}x${height})`);
